version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solitaire
#    restart: unless-stopped
    ports:
      - 8080:8080
    env_file:
      - ./env/docker.env
      - ./env/.env
    volumes:
      - ./logs/:/app/logs
    command: ["python", "main.py"]
